# Generated by Django 4.1.5 on 2023-01-26 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0003_station_created_at_station_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='station',
            name='updated_at',
        ),
    ]
