# Generated by Django 4.1.5 on 2023-02-15 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0005_station_created_at_station_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='active',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
