# Generated by Django 4.1.5 on 2023-02-14 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentbike',
            name='status',
            field=models.CharField(blank=True, default='sended', max_length=100),
        ),
        migrations.AddField(
            model_name='incidentother',
            name='status',
            field=models.CharField(blank=True, default='sended', max_length=100),
        ),
        migrations.AddField(
            model_name='incidentslot',
            name='status',
            field=models.CharField(blank=True, default='sended', max_length=100),
        ),
    ]
