# Generated by Django 4.1.5 on 2023-02-14 17:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('avatar', models.CharField(blank=True, default='https://i.postimg.cc/W41QygPj/descarga.png', max_length=100)),
                ('biography', models.CharField(blank=True, default='User active with rent bikes', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
