# Generated by Django 4.1.5 on 2023-02-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_profile_user_profileusr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileusr',
            name='avatar',
            field=models.CharField(blank=True, default='https://i.postimg.cc/T3g6d9nk/image.png', max_length=100),
        ),
    ]
