# Generated by Django 4.1.5 on 2023-02-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_profileusr_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chatID',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
