# Generated by Django 4.1.5 on 2023-02-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_chatid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileusr',
            name='notis',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
