# Generated by Django 4.1.5 on 2023-01-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
