# Generated by Django 4.1.5 on 2023-01-26 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('slot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False, max_length=100, unique=True)),
                ('status', models.BooleanField(blank=True, default=True)),
                ('pfm', models.FloatField(blank=True, default=0.05, max_length=255)),
                ('img_bike', models.CharField(blank=True, default='img', max_length=100)),
                ('id_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slot.slot')),
            ],
            options={
                'verbose_name_plural': 'Stations',
            },
        ),
    ]
