# Generated by Django 4.1.5 on 2023-01-26 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bike',
            options={'verbose_name_plural': 'Bikes'},
        ),
        migrations.RenameField(
            model_name='bike',
            old_name='id_slot',
            new_name='slot',
        ),
    ]
