# Generated by Django 4.1.5 on 2023-01-26 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0002_rename_id_station_slot_station'),
        ('bike', '0002_alter_bike_options_rename_id_slot_bike_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='slot.slot'),
        ),
    ]
