# Generated by Django 4.1.5 on 2023-01-26 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0004_bike_created_at_bike_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='updated_at',
        ),
    ]
