# Generated by Django 4.1.5 on 2023-02-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0006_bike_created_at_bike_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='img_bike',
            field=models.CharField(blank=True, default='https://deepinmummymatters.com/wp-content/uploads/2019/05/bike-renting.jpg', max_length=100),
        ),
    ]
