# Generated by Django 4.1.5 on 2023-01-26 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('station', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False, max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('id_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='station.station')),
            ],
            options={
                'verbose_name_plural': 'Slots',
            },
        ),
    ]
