# Generated by Django 4.1.5 on 2023-01-26 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slot',
            old_name='id_station',
            new_name='station',
        ),
    ]
