# Generated by Django 4.1.5 on 2023-01-26 18:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0002_rename_id_station_slot_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='slot',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
