# Generated by Django 4.1.5 on 2023-01-26 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0003_slot_created_at_slot_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='updated_at',
        ),
    ]
